name: Heroku Deploy

on:
  pull_request:
    types: [closed]
    branches:
      - main
# `types: [closed]` above means that this step runs even when a PR is
# closed without merging.
# This `if` statement ensures we only run this step when the PR is merged.
if: ${{ github.event.pull_request.merged == true }}

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Deploy to Heroku staging
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STAGING_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Deploy to Heroku production
        uses: akhileshns/heroku-deploy@v3.12.12
        # Only run for PRs that merge to the `main` branch
        if: ${{ env.GITHUB_BASE_REF == 'main' }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_PRODUCTION_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
